### ISSUE TITLE
Duplication explanation

### ISSUE THREAD

**Issue by robofar** [turandai/gaussian_surfels#37]
Hello. I have question for following code snippet (from method `create_from_pcd` inside `GaussianModel` class):
```
if self.config[0] > 0:
    if np.abs(np.sum(pcd.normals)) < 1:
        dup = 4
        fused_point_cloud = torch.cat([fused_point_cloud for _ in range(dup)], 0)
        fused_color = torch.cat([fused_color for _ in range(dup)], 0)
        scales = torch.cat([scales for _ in range(dup)], 0)
        normals = np.random.rand(len(fused_point_cloud), 3) - 0.5
        normals /= np.linalg.norm(normals, 2, 1, True)
    else:
        normals = pcd.normals
```

I don't understand two things here:

- `np.abs(np.sum(pcd.normals)) < 1`: What does this statement means?
- `dup=4`: why you duplicating 4 times in case statement above is satisfied?

Thank you!

**Comment by turandai** [comment]
Hi, gaussian surfels are rendered with back-face culling, meaning you can not see some points from some perspective. I duplicates the sfm points at the same position with random normal to fully utilize it, so that it can be seen from more perspective. This is helpful in some cases. As for the condition ```np.abs(np.sum(pcd.normals)) < 1```, I just did this in a very simple way, please feel free to design a better condition.
